### ISSUE TITLE
Remove animation from http://skew-lang.org/

### ISSUE THREAD

**Issue by mingodad** [evanw/skew#10]
Hello !
What's the point of burn cpu while reading the documentation on http://skew-lang.org/, can you remove that animation ?
Cheers !

**Comment by mindplay-dk** [comment]
The overhead is ~1% on my system, is it really that bad on yours?

**Comment by kritzikratzi** [comment]
it's pretty bad on my computer (mbp retina, mid 2012)

firefox: 100% of one core
chrome: 70% of one core
safari: 1% of one core

might have something to do with my semi broken graphics card. i wonder if others get the same results.

**Comment by mingodad** [comment]
If it was not that bad I would not created this issue.

**Comment by mindplay-dk** [comment]
I'm guessing no hardware acceleration. Sounds like a driver issue.

**Comment by kritzikratzi** [comment]
@mindplay-dk seeing that safari takes no cpu, it seems a bit like an issue in firefox and chrome.

**Comment by evanw** [comment]
I'm definitely planning on using a different design for the website at some point. :) It's just not as high on my todo list as improving the compiler tech.

**Comment by evanw** [comment]
It has now been removed.

**Comment by mindplay-dk** [comment]
Not even a still image, that's kinda sad ;-)
